version: '3'
services:
    riemann:
        image: riemannio/riemann:latest
        ports:
          - "127.0.0.1:5555:5555"
          - "127.0.0.1:5555:5555/udp"
          - "127.0.0.1:5556:5556"
        volumes:
          - ./riemann/riemann.config:/etc/riemann.config
        environment:
          - DATADOGKEY=${DATADOGKEY}
          - UNIFORMHOST=${UNIFORMHOST}
    riemann-dash:
        build: ./riemann-dash
        ports:
          - "4567:4567"
        volumes:
          - "./riemann-dash/config.json:/riemann-dash/config.json"
